//Product action types
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GETTING_PRODUCTS_FAILED = "GETTING_PRODUCTS_FAILED";

export const GET_SINGLE_PRODUCT_START = "GET_SINGLE_PRODUCT_START";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAILED = "GET_SINGLE_PRODUCT_FAILED";

export const ADD_PRODUCT_CHANGE_HANDLER = "ADD_PRODUCT_CHANGE_HANDLER";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_START = "UPDATE_PRODUCT_START";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";
export const UPDATE_CHANGE_HANDLER = "UPDATE_CHANGE_HANDLER"; //Input change handler

export const SHOW_UPDATE_PRODUCT_MODAL = "SHOW_UPDATE_PRODUCT_MODAL";
export const HIDE_UPDATE_PRODUCT_MODAL = "HIDE_UPDATE_PRODUCT_MODAL";

export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const SHOW_DELETE_PRODUCT_MODAL = "SHOW_DELETE_PRODUCT_MODAL";
export const HIDE_DELETE_PRODUCT_MODAL = "HIDE_DELETE_PRODUCT_MODAL";

export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";

//Register action types
export const REGISTER_CHANGE_HANDLER = "REGISTER_CHANGE_HANDLER"; //On Change handler
export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";

//Login action types
export const LOGIN_CHANGE_HANDLER = "LOGIN_CHANGE_HANDLER";
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";

//Logout user action type
export const LOGOUT_USER = "LOGOUT_USER";

//Disable errors action type
export const DISABLE_ERRORS = "DISABLE_ERROR";

//Cart action types
export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";

export const GET_CART_PRODUCTS_START = "GET_CART_PRODUCTS_START";
export const GET_CART_PRODUCTS_SUCCESS = "GET_CART_PRODUCTS_SUCCESS";
export const GET_CART_PRODUCTS_FAILED = "GET_CART_PRODUCTS_FAILED";

export const CLEAR_CART_START = "CLEAR_CART_START";
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
export const CLEAR_CART_FAILED = "CLEAR_CART_FAILED";

//Order action types
export const SHOW_PURCHASE_MODAL = "SHOW_PURCHASE_MODAL";
export const HIDE_PURCHASE_MODAL = "HIDE_PURCHASE_MODAL";

export const PURCHASE_START = "PURCHASE_START";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAILED = "PURCHASE_FAILED";

export const GET_USER_ORDERS_START = "GET_USER_ORDERS_START";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";
export const GET_USER_ORDERS_FAILED = "GET_USER_ORDERS_FAILED";

export const PURCHASE_CHANGE_HANDLER = "PURCHASE_CHANGE_HANDLER";

//Side drawer actions

export const SHOW_SIDE_DRAWER = "SHOW_SIDE_DRAWER";
export const HIDE_SIDE_DRAWER = "HIDE_SIDE_DRAWER";
